// $ANTLR : "expectHereDocEnd.g" -> "LexExpectHereDocEnd.java"$

// This source file was generated by ANTLR. Do not edit manually!
package org.epic.core.parser;

public interface LexExpectHereDocEndTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int CLOSE_HEREDOC = 4;
	int HEREDOC_LINE = 5;
	int HEREDOC_LINE_CHARS = 6;
	int NEWLINE = 7;
	int NOTNEWLINE = 8;
}
