// $ANTLR : "perl.g" -> "PerlLexer.java"$

// This source file was generated by ANTLR. Do not edit manually!
package org.epic.core.parser;

import java.io.InputStream;
import antlr.TokenStreamException;
import antlr.TokenStreamIOException;
import antlr.TokenStreamRecognitionException;
import antlr.CharStreamException;
import antlr.CharStreamIOException;
import antlr.ANTLRException;
import java.io.Reader;
import java.util.Hashtable;
import antlr.CharScanner;
import antlr.InputBuffer;
import antlr.ByteBuffer;
import antlr.CharBuffer;
import antlr.Token;
import antlr.CommonToken;
import antlr.RecognitionException;
import antlr.NoViableAltForCharException;
import antlr.MismatchedCharException;
import antlr.TokenStream;
import antlr.ANTLRHashString;
import antlr.LexerSharedInputState;
import antlr.collections.impl.BitSet;
import antlr.SemanticException;

public class PerlLexer extends org.epic.core.parser.PerlLexerBase implements PerlTokenTypes, TokenStream
 {
public PerlLexer(InputStream in) {
	this(new ByteBuffer(in));
}
public PerlLexer(Reader in) {
	this(new CharBuffer(in));
}
public PerlLexer(InputBuffer ib) {
	this(new LexerSharedInputState(ib));
}
public PerlLexer(LexerSharedInputState state) {
	super(state);
	caseSensitiveLiterals = true;
	setCaseSensitive(true);
	literals = new Hashtable();
}

public Token nextToken() throws TokenStreamException {
	Token theRetToken=null;
tryAgain:
	for (;;) {
		Token _token = null;
		int _ttype = Token.INVALID_TYPE;
		resetText();
		try {   // for char stream error handling
			try {   // for lexical error handling
				if ((LA(1)=='#') && ((LA(2) >= '\u0000' && LA(2) <= '\uffff'))) {
					mCOMMENT(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='&') && (LA(2)=='&') && (true) && (true)) {
					mOPER_AND(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='|') && (LA(2)=='|')) {
					mOPER_OR(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='<') && (LA(2)=='=') && (true) && (true)) {
					mOPER_LTEQ(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='>') && (LA(2)=='=')) {
					mOPER_GTEQ(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='-') && (LA(2)=='s')) {
					mOPER_S(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='=') && (LA(2)=='>')) {
					mOPER_DARROW(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='-') && (LA(2)=='>')) {
					mOPER_ARROW(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='=') && (LA(2)=='=')) {
					mOPER_DOUBLEEQ(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='!') && (LA(2)=='=')) {
					mOPER_NOTEQ(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='=') && (LA(2)=='~')) {
					mOPER_EQMATCH(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='!') && (LA(2)=='~')) {
					mOPER_EQNOTMATCH(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='-') && (LA(2)=='-')) {
					mOPER_MINUSMINUS(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='-') && (LA(2)=='=')) {
					mOPER_MINUSEQ(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='+') && (LA(2)=='+')) {
					mOPER_PLUSPLUS(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='+') && (LA(2)=='=')) {
					mOPER_PLUSEQ(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='.') && (LA(2)=='.')) {
					mOPER_DOTDOT(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='&') && (_tokenSet_0.member(LA(2))) && (true) && (true)) {
					mPROC_REF(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='<') && (LA(2)=='<')) {
					mOPER_LSHIFT_OR_HEREDOC(true);
					theRetToken=_returnToken;
				}
				else if (((LA(1)=='<') && (_tokenSet_1.member(LA(2))) && (true) && (true))&&( glob )) {
					mGLOB(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='>') && (LA(2)=='>')) {
					mOPER_RSHIFT(true);
					theRetToken=_returnToken;
				}
				else if (((LA(1)=='=') && (_tokenSet_0.member(LA(2))))&&( getColumn() == 1 )) {
					mOPEN_POD(true);
					theRetToken=_returnToken;
				}
				else if ((_tokenSet_2.member(LA(1))) && (true) && (true) && (true)) {
					mWS(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)==';') && (true) && (true) && (true)) {
					mSEMI(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='{') && (true) && (true) && (true)) {
					mOPEN_CURLY(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='}') && (true) && (true) && (true)) {
					mCLOSE_CURLY(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='`') && (true) && (true) && (true)) {
					mOPEN_BQUOTE(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='\'') && (true) && (true) && (true)) {
					mOPEN_SQUOTE(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='"') && (true) && (true) && (true)) {
					mOPEN_DQUOTE(true);
					theRetToken=_returnToken;
				}
				else if (((_tokenSet_3.member(LA(1))) && (true) && (true) && (true))&&( !proto )) {
					mMAYBE_SPECIAL_VAR(true);
					theRetToken=_returnToken;
				}
				else if (((_tokenSet_4.member(LA(1))) && (true) && (true) && (true))&&( proto )) {
					mPROTO(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='/') && (true) && (true) && (true)) {
					mOPEN_SLASH(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='?') && (true) && (true) && (true)) {
					mOPEN_QMARK(true);
					theRetToken=_returnToken;
				}
				else if ((_tokenSet_0.member(LA(1))) && (true) && (true) && (true)) {
					mSUBST_OR_MATCH_OR_WORD(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)==',') && (true) && (true) && (true)) {
					mOPER_COMMA(true);
					theRetToken=_returnToken;
				}
				else if (((LA(1)=='=') && (true) && (true) && (true))&&( !format )) {
					mOPER_EQ(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='/') && (true) && (true) && (true)) {
					mOPER_DIV(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='+') && (true) && (true) && (true)) {
					mOPER_PLUS(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='-') && (true) && (true) && (true)) {
					mOPER_MINUS(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='.') && (true) && (true) && (true)) {
					mOPER_DOT(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='\\') && (true) && (true) && (true)) {
					mOPER_BSLASH(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='(') && (true) && (true) && (true)) {
					mOPEN_PAREN(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)==')') && (true) && (true) && (true)) {
					mCLOSE_PAREN(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='[') && (true) && (true) && (true)) {
					mOPEN_BRACKET(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)==']') && (true) && (true) && (true)) {
					mCLOSE_BRACKET(true);
					theRetToken=_returnToken;
				}
				else if (((LA(1)=='=') && (true) && (true) && (true))&&( format )) {
					mFORMAT_STMT(true);
					theRetToken=_returnToken;
				}
				else if ((LA(1)=='>') && (true) && (true) && (true)) {
					mOPER_GT(true);
					theRetToken=_returnToken;
				}
				else if (((LA(1)=='<') && (true) && (true) && (true))&&( !glob )) {
					mOPER_LT(true);
					theRetToken=_returnToken;
				}
				else if (((LA(1) >= '\u0000' && LA(1) <= '\ufffe')) && (true) && (true) && (true)) {
					mOTHER(true);
					theRetToken=_returnToken;
				}
				else {
					if (LA(1)==EOF_CHAR) {uponEOF(); _returnToken = makeToken(Token.EOF_TYPE);}
				else {throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());}
				}
				
				if ( _returnToken==null ) continue tryAgain; // found SKIP token
				_ttype = _returnToken.getType();
				_ttype = testLiteralsTable(_ttype);
				_returnToken.setType(_ttype);
				return _returnToken;
			}
			catch (RecognitionException e) {
				throw new TokenStreamRecognitionException(e);
			}
		}
		catch (CharStreamException cse) {
			if ( cse instanceof CharStreamIOException ) {
				throw new TokenStreamIOException(((CharStreamIOException)cse).io);
			}
			else {
				throw new TokenStreamException(cse.getMessage());
			}
		}
	}
}

	public final void mWS(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = WS;
		int _saveIndex;
		
		{
		int _cnt1570=0;
		_loop1570:
		do {
			if ((LA(1)==' ') && (true) && (true) && (true)) {
				match(' ');
			}
			else if ((LA(1)=='\t') && (true) && (true) && (true)) {
				match('\t');
			}
			else if ((LA(1)=='\n'||LA(1)=='\r') && (true) && (true) && (true)) {
				mNEWLINE(false);
			}
			else {
				if ( _cnt1570>=1 ) { break _loop1570; } else {throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());}
			}
			
			_cnt1570++;
		} while (true);
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mNEWLINE(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = NEWLINE;
		int _saveIndex;
		
		{
		if ((LA(1)=='\r') && (LA(2)=='\n') && (true) && (true)) {
			match('\r');
			match('\n');
		}
		else if ((LA(1)=='\r') && (true) && (true) && (true)) {
			match('\r');
		}
		else if ((LA(1)=='\n')) {
			match('\n');
		}
		else {
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		
		}
		if ( inputState.guessing==0 ) {
			_ttype = Token.SKIP; newline();
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mCOMMENT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = COMMENT;
		int _saveIndex;
		
		match('#');
		{
		_loop1573:
		do {
			if ((_tokenSet_5.member(LA(1)))) {
				mNOT_NEWLINE(false);
			}
			else {
				break _loop1573;
			}
			
		} while (true);
		}
		{
		switch ( LA(1)) {
		case '\n':  case '\r':
		{
			_saveIndex=text.length();
			mNEWLINE(false);
			text.setLength(_saveIndex);
			break;
		}
		case '\uffff':
		{
			_saveIndex=text.length();
			match('\uFFFF');
			text.setLength(_saveIndex);
			break;
		}
		default:
		{
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		}
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mNOT_NEWLINE(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = NOT_NEWLINE;
		int _saveIndex;
		
		{
		match(_tokenSet_5);
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mSEMI(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = SEMI;
		int _saveIndex;
		
		match(';');
		if ( inputState.guessing==0 ) {
			
					format = glob = afterArrow = afterDArrow = false;
					qmarkRegexp = slashRegexp = true;
					_token = createOperatorToken(PerlTokenTypes.SEMI, ";");
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPEN_CURLY(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_CURLY;
		int _saveIndex;
		
		match('{');
		if ( inputState.guessing==0 ) {
			
					_token = createCurlyToken(PerlTokenTypes.OPEN_CURLY, "{"); pc++;
					proto = glob = afterSub = false;
					qmarkRegexp = slashRegexp = true;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mCLOSE_CURLY(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = CLOSE_CURLY;
		int _saveIndex;
		
		match('}');
		if ( inputState.guessing==0 ) {
			
					pc--; _token = createCurlyToken(PerlTokenTypes.CLOSE_CURLY, "}");
					qmarkRegexp = slashRegexp = format = glob = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPEN_BQUOTE(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_BQUOTE;
		int _saveIndex;
		
		match('`');
		if ( inputState.guessing==0 ) {
			getParent().expectStringEnd('`');
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPEN_SQUOTE(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_SQUOTE;
		int _saveIndex;
		
		match('\'');
		if ( inputState.guessing==0 ) {
				getParent().expectStringEnd('\'');
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPEN_DQUOTE(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_DQUOTE;
		int _saveIndex;
		
		match('"');
		if ( inputState.guessing==0 ) {
			getParent().expectStringEnd('"');
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mMAYBE_SPECIAL_VAR(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = MAYBE_SPECIAL_VAR;
		int _saveIndex;
		
		if (!( !proto ))
		  throw new SemanticException(" !proto ");
		{
		boolean synPredMatched1584 = false;
		if (((LA(1)=='*') && (LA(2)=='*') && (true) && (true))) {
			int _m1584 = mark();
			synPredMatched1584 = true;
			inputState.guessing++;
			try {
				{
				match("**");
				}
			}
			catch (RecognitionException pe) {
				synPredMatched1584 = false;
			}
			rewind(_m1584);
inputState.guessing--;
		}
		if ( synPredMatched1584 ) {
			match("**");
			if ( inputState.guessing==0 ) {
				_token = createOperatorToken(PerlTokenTypes.OPER_MULMUL, "**");
			}
		}
		else {
			boolean synPredMatched1586 = false;
			if (((LA(1)=='*') && (LA(2)=='=') && (true) && (true))) {
				int _m1586 = mark();
				synPredMatched1586 = true;
				inputState.guessing++;
				try {
					{
					match("*=");
					}
				}
				catch (RecognitionException pe) {
					synPredMatched1586 = false;
				}
				rewind(_m1586);
inputState.guessing--;
			}
			if ( synPredMatched1586 ) {
				match("*=");
				if ( inputState.guessing==0 ) {
					_token = createOperatorToken(PerlTokenTypes.OPER_MULEQ, "*=");
				}
			}
			else {
				boolean synPredMatched1588 = false;
				if (((LA(1)=='$'||LA(1)=='%'||LA(1)=='@') && (_tokenSet_6.member(LA(2))) && (true) && (true))) {
					int _m1588 = mark();
					synPredMatched1588 = true;
					inputState.guessing++;
					try {
						{
						mVAR(false);
						}
					}
					catch (RecognitionException pe) {
						synPredMatched1588 = false;
					}
					rewind(_m1588);
inputState.guessing--;
				}
				if ( synPredMatched1588 ) {
					mVAR(false);
					if ( inputState.guessing==0 ) {
						_ttype = PerlTokenTypes.VAR;
					}
				}
				else {
					boolean synPredMatched1590 = false;
					if (((_tokenSet_3.member(LA(1))) && (_tokenSet_7.member(LA(2))) && (true) && (true))) {
						int _m1590 = mark();
						synPredMatched1590 = true;
						inputState.guessing++;
						try {
							{
							mSPECIAL_VAR(false);
							}
						}
						catch (RecognitionException pe) {
							synPredMatched1590 = false;
						}
						rewind(_m1590);
inputState.guessing--;
					}
					if ( synPredMatched1590 ) {
						mSPECIAL_VAR(false);
						if ( inputState.guessing==0 ) {
							_ttype = PerlTokenTypes.SPECIAL_VAR; glob = false;
						}
					}
					else {
						boolean synPredMatched1594 = false;
						if (((LA(1)=='%') && (LA(2)=='=') && (true) && (true))) {
							int _m1594 = mark();
							synPredMatched1594 = true;
							inputState.guessing++;
							try {
								{
								match("%=");
								}
							}
							catch (RecognitionException pe) {
								synPredMatched1594 = false;
							}
							rewind(_m1594);
inputState.guessing--;
						}
						if ( synPredMatched1594 ) {
							match("%=");
							if ( inputState.guessing==0 ) {
								_token = createOperatorToken(PerlTokenTypes.OPER_MODEQ, "%=");
							}
						}
						else {
							boolean synPredMatched1592 = false;
							if (((LA(1)=='*') && (true))) {
								int _m1592 = mark();
								synPredMatched1592 = true;
								inputState.guessing++;
								try {
									{
									match('*');
									}
								}
								catch (RecognitionException pe) {
									synPredMatched1592 = false;
								}
								rewind(_m1592);
inputState.guessing--;
							}
							if ( synPredMatched1592 ) {
								match('*');
								if ( inputState.guessing==0 ) {
									_token = createOperatorToken(PerlTokenTypes.OPER_MUL, "*");
								}
							}
							else {
								boolean synPredMatched1596 = false;
								if (((LA(1)=='%') && (true) && (true) && (true))) {
									int _m1596 = mark();
									synPredMatched1596 = true;
									inputState.guessing++;
									try {
										{
										match('%');
										}
									}
									catch (RecognitionException pe) {
										synPredMatched1596 = false;
									}
									rewind(_m1596);
inputState.guessing--;
								}
								if ( synPredMatched1596 ) {
									match('%');
									if ( inputState.guessing==0 ) {
										_token = createOperatorToken(PerlTokenTypes.OPER_MOD, "%");
									}
								}
								else {
									boolean synPredMatched1598 = false;
									if (((LA(1)=='$'||LA(1)=='%'||LA(1)=='@') && (true) && (true) && (true))) {
										int _m1598 = mark();
										synPredMatched1598 = true;
										inputState.guessing++;
										try {
											{
											mVAR_START(false);
											}
										}
										catch (RecognitionException pe) {
											synPredMatched1598 = false;
										}
										rewind(_m1598);
inputState.guessing--;
									}
									if ( synPredMatched1598 ) {
										mVAR_START(false);
										if ( inputState.guessing==0 ) {
											_ttype = PerlTokenTypes.VAR;
										}
									}
									else {
										throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
									}
									}}}}}}}
									}
									if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
										_token = makeToken(_ttype);
										_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
									}
									_returnToken = _token;
								}
								
	protected final void mVAR(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = VAR;
		int _saveIndex;
		
		if (!( !proto ))
		  throw new SemanticException(" !proto ");
		mVAR_START(false);
		{
		switch ( LA(1)) {
		case '0':  case '1':  case '2':  case '3':
		case '4':  case '5':  case '6':  case '7':
		case '8':  case '9':  case ':':  case 'A':
		case 'B':  case 'C':  case 'D':  case 'E':
		case 'F':  case 'G':  case 'H':  case 'I':
		case 'J':  case 'K':  case 'L':  case 'M':
		case 'N':  case 'O':  case 'P':  case 'Q':
		case 'R':  case 'S':  case 'T':  case 'U':
		case 'V':  case 'W':  case 'X':  case 'Y':
		case 'Z':  case '_':  case 'a':  case 'b':
		case 'c':  case 'd':  case 'e':  case 'f':
		case 'g':  case 'h':  case 'i':  case 'j':
		case 'k':  case 'l':  case 'm':  case 'n':
		case 'o':  case 'p':  case 'q':  case 'r':
		case 's':  case 't':  case 'u':  case 'v':
		case 'w':  case 'x':  case 'y':  case 'z':
		{
			mID(false);
			break;
		}
		case '{':
		{
			mCURLY(false);
			break;
		}
		case '@':
		{
			match('@');
			break;
		}
		case '\uffff':
		{
			_saveIndex=text.length();
			match('\uFFFF');
			text.setLength(_saveIndex);
			break;
		}
		default:
		{
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		}
		}
		if ( inputState.guessing==0 ) {
			glob = qmarkRegexp = slashRegexp = false;
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mSPECIAL_VAR(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = SPECIAL_VAR;
		int _saveIndex;
		
		{
		if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='A')) {
			match("*^A");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='C')) {
			match("*^C");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='D')) {
			match("*^D");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='E')) {
			match("*^E");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='F')) {
			match("*^F");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='I')) {
			match("*^I");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='L')) {
			match("*^L");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='N')) {
			match("*^N");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='O')) {
			match("*^O");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='P')) {
			match("*^P");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='R')) {
			match("*^R");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='S')) {
			match("*^S");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='T')) {
			match("*^T");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='V')) {
			match("*^V");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='W')) {
			match("*^W");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (LA(3)=='X')) {
			match("*^X");
		}
		else if ((LA(1)=='$') && (LA(2)=='$') && (LA(3)=='m')) {
			match("$$m");
		}
		else if ((LA(1)=='$') && (LA(2)=='$') && (LA(3)=='s')) {
			match("$$s");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='A')) {
			match("$^A");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='C')) {
			match("$^C");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='D')) {
			match("$^D");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='E')) {
			match("$^E");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='F')) {
			match("$^F");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='H')) {
			match("$^H");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='I')) {
			match("$^I");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='L')) {
			match("$^L");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='M')) {
			match("$^M");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='N')) {
			match("$^N");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='O')) {
			match("$^O");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='P')) {
			match("$^P");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='R')) {
			match("$^R");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='S')) {
			match("$^S");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='T')) {
			match("$^T");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='V')) {
			match("$^V");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='W')) {
			match("$^W");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (LA(3)=='X')) {
			match("$^X");
		}
		else if ((LA(1)=='*') && (LA(2)=='/')) {
			match("*/");
		}
		else if ((LA(1)=='*') && (LA(2)=='?')) {
			match("*?");
		}
		else if ((LA(1)=='*') && (LA(2)=='%')) {
			match("*%");
		}
		else if ((LA(1)=='*') && (LA(2)=='@')) {
			match("*@");
		}
		else if ((LA(1)=='*') && (LA(2)=='_')) {
			match("*_");
		}
		else if ((LA(1)=='*') && (LA(2)=='-')) {
			match("*-");
		}
		else if ((LA(1)=='*') && (LA(2)=='+')) {
			match("*+");
		}
		else if ((LA(1)=='*') && (LA(2)=='.')) {
			match("*.");
		}
		else if ((LA(1)=='*') && (LA(2)=='|')) {
			match("*|");
		}
		else if ((LA(1)=='*') && (LA(2)==',')) {
			match("*,");
		}
		else if ((LA(1)=='*') && (LA(2)==';')) {
			match("*;");
		}
		else if ((LA(1)=='*') && (LA(2)=='~')) {
			match("*~");
		}
		else if ((LA(1)=='*') && (LA(2)==':')) {
			match("*:");
		}
		else if ((LA(1)=='*') && (LA(2)=='^') && (true)) {
			match("*^");
		}
		else if ((LA(1)=='*') && (LA(2)=='<')) {
			match("*<");
		}
		else if ((LA(1)=='*') && (LA(2)=='>')) {
			match("*>");
		}
		else if ((LA(1)=='*') && (LA(2)=='(')) {
			match("*(");
		}
		else if ((LA(1)=='*') && (LA(2)==')')) {
			match("*)");
		}
		else if ((LA(1)=='*') && (LA(2)=='"')) {
			match("*\"");
		}
		else if ((LA(1)=='*') && (LA(2)=='\\')) {
			match("*\\");
		}
		else if ((LA(1)=='$') && (LA(2)=='/')) {
			match("$/");
		}
		else if ((LA(1)=='$') && (LA(2)=='?')) {
			match("$?");
		}
		else if ((LA(1)=='$') && (LA(2)=='%')) {
			match("$%");
		}
		else if ((LA(1)=='$') && (LA(2)=='@')) {
			match("$@");
		}
		else if ((LA(1)=='$') && (LA(2)=='_')) {
			match("$_");
		}
		else if ((LA(1)=='$') && (LA(2)=='-')) {
			match("$-");
		}
		else if ((LA(1)=='$') && (LA(2)=='+')) {
			match("$+");
		}
		else if ((LA(1)=='$') && (LA(2)=='.')) {
			match("$.");
		}
		else if ((LA(1)=='$') && (LA(2)=='|')) {
			match("$|");
		}
		else if ((LA(1)=='$') && (LA(2)=='!')) {
			match("$!");
		}
		else if ((LA(1)=='$') && (LA(2)==';')) {
			match("$;");
		}
		else if ((LA(1)=='$') && (LA(2)=='~')) {
			match("$~");
		}
		else if ((LA(1)=='$') && (LA(2)=='$') && (true)) {
			match("$$");
		}
		else if ((LA(1)=='$') && (LA(2)=='`')) {
			match("$`");
		}
		else if ((LA(1)=='$') && (LA(2)=='\'')) {
			match("$'");
		}
		else if ((LA(1)=='$') && (LA(2)=='<')) {
			match("$<");
		}
		else if ((LA(1)=='$') && (LA(2)=='>')) {
			match("$>");
		}
		else if ((LA(1)=='$') && (LA(2)=='(')) {
			match("$(");
		}
		else if ((LA(1)=='$') && (LA(2)==')')) {
			match("$)");
		}
		else if ((LA(1)=='$') && (LA(2)==',')) {
			match("$,");
		}
		else if ((LA(1)=='$') && (LA(2)=='[')) {
			match("$[");
		}
		else if ((LA(1)=='$') && (LA(2)==']')) {
			match("$]");
		}
		else if ((LA(1)=='$') && (LA(2)==':')) {
			match("$:");
		}
		else if ((LA(1)=='$') && (LA(2)=='*')) {
			match("$*");
		}
		else if ((LA(1)=='$') && (LA(2)=='#')) {
			match("$#");
		}
		else if ((LA(1)=='$') && (LA(2)=='=')) {
			match("$=");
		}
		else if ((LA(1)=='$') && (LA(2)=='^') && (true)) {
			match("$^");
		}
		else if ((LA(1)=='$') && (LA(2)=='&')) {
			match("$&");
		}
		else if ((LA(1)=='$') && (LA(2)=='"')) {
			match("$\"");
		}
		else if ((LA(1)=='$') && (LA(2)=='\\')) {
			match("$\\");
		}
		else if ((LA(1)=='@') && (LA(2)=='+')) {
			match("@+");
		}
		else if ((LA(1)=='@') && (LA(2)=='-')) {
			match("@-");
		}
		else if ((LA(1)=='@') && (LA(2)=='_')) {
			match("@_");
		}
		else if ((LA(1)=='@') && (LA(2)=='$')) {
			match("@$");
		}
		else if ((LA(1)=='%') && (LA(2)=='!')) {
			match("%!");
		}
		else if ((LA(1)=='%') && (LA(2)=='@')) {
			match("%@");
		}
		else if ((LA(1)=='%') && (LA(2)=='^')) {
			match("%^H");
		}
		else {
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mVAR_START(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = VAR_START;
		int _saveIndex;
		
		{
		switch ( LA(1)) {
		case '@':
		{
			match('@');
			break;
		}
		case '$':
		{
			match('$');
			break;
		}
		case '%':
		{
			match('%');
			break;
		}
		default:
		{
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		}
		}
		{
		_loop1611:
		do {
			switch ( LA(1)) {
			case '$':
			{
				match('$');
				break;
			}
			case '%':
			{
				match('%');
				break;
			}
			case '*':
			{
				match('*');
				break;
			}
			case '#':
			{
				match('#');
				break;
			}
			default:
				if ((LA(1)=='@') && (true) && (true) && (true)) {
					match('@');
				}
			else {
				break _loop1611;
			}
			}
		} while (true);
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mOPER_MODEQ(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_MODEQ;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mOPER_MULEQ(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_MULEQ;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mOPER_MULMUL(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_MULMUL;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mOPER_MUL(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_MUL;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mOPER_MOD(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_MOD;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mID(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = ID;
		int _saveIndex;
		
		if ( inputState.guessing==0 ) {
			afterColon = false;
		}
		{
		int _cnt1748=0;
		_loop1748:
		do {
			if ((_tokenSet_0.member(LA(1))) && (true) && (true) && (true)) {
				if ( inputState.guessing==0 ) {
					
							// keep going if we have "::", break on ":"
							// there must be a better way to implement it X-(
							if (LA(1) == ':') 
							{
								if (!afterColon && LA(2) != ':') break;
								else afterColon = true;
							}
							else afterColon = false;
						
				}
				mWORD_CHAR(false);
			}
			else {
				if ( _cnt1748>=1 ) { break _loop1748; } else {throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());}
			}
			
			_cnt1748++;
		} while (true);
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mCURLY(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = CURLY;
		int _saveIndex;
		
		match('{');
		{
		_loop1615:
		do {
			if ((LA(1)=='{') && ((LA(2) >= '\u0000' && LA(2) <= '\uffff')) && ((LA(3) >= '\u0000' && LA(3) <= '\uffff')) && (true)) {
				mCURLY(false);
			}
			else if ((LA(1)=='\n'||LA(1)=='\r') && ((LA(2) >= '\u0000' && LA(2) <= '\uffff')) && (true) && (true)) {
				mNEWLINE(false);
			}
			else if ((_tokenSet_8.member(LA(1))) && ((LA(2) >= '\u0000' && LA(2) <= '\uffff')) && (true) && (true)) {
				{
				match(_tokenSet_8);
				}
			}
			else {
				break _loop1615;
			}
			
		} while (true);
		}
		{
		switch ( LA(1)) {
		case '}':
		{
			match('}');
			break;
		}
		case '\uffff':
		{
			_saveIndex=text.length();
			match('\uFFFF');
			text.setLength(_saveIndex);
			break;
		}
		default:
		{
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		}
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_AND(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_AND;
		int _saveIndex;
		
		match("&&");
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_AND, "&&");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_OR(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_OR;
		int _saveIndex;
		
		match("||");
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_OR, "||");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_LTEQ(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_LTEQ;
		int _saveIndex;
		
		match("<=");
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_LTEQ, "<=");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_GTEQ(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_GTEQ;
		int _saveIndex;
		
		match(">=");
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_GTEQ, ">=");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mPROTO(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = PROTO;
		int _saveIndex;
		
		if (!( proto ))
		  throw new SemanticException(" proto ");
		{
		int _cnt1623=0;
		_loop1623:
		do {
			switch ( LA(1)) {
			case '$':
			{
				match('$');
				break;
			}
			case '@':
			{
				match('@');
				break;
			}
			case '%':
			{
				match('%');
				break;
			}
			case '*':
			{
				match('*');
				break;
			}
			case ';':
			{
				match(';');
				break;
			}
			case '\\':
			{
				match('\\');
				break;
			}
			case '&':
			{
				match('&');
				break;
			}
			case '_':
			{
				match('_');
				break;
			}
			case '\t':  case '\n':  case '\r':  case ' ':
			{
				mWS(false);
				break;
			}
			default:
			{
				if ( _cnt1623>=1 ) { break _loop1623; } else {throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());}
			}
			}
			_cnt1623++;
		} while (true);
		}
		if ( inputState.guessing==0 ) {
			proto = false;
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_S(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_S;
		int _saveIndex;
		
		match("-s");
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_S, "-s");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPEN_SLASH(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_SLASH;
		int _saveIndex;
		
		match('/');
		if ( inputState.guessing==0 ) {
			
					if (slashRegexp)
					{
					getParent().expectStringSuffix(); // second
					getParent().expectStringEnd('/'); // first
					slashRegexp = qmarkRegexp = false;
					}
					else
					{
						_token = createOperatorToken(PerlTokenTypes.OPER_DIV, "/");
					}
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mOPER_QMARK(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_QMARK;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPEN_QMARK(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_QMARK;
		int _saveIndex;
		
		match('?');
		if ( inputState.guessing==0 ) {
			
					if (qmarkRegexp)
					{
					getParent().expectStringSuffix(); // second
					getParent().expectStringEnd('?'); // first
					slashRegexp = qmarkRegexp = false;
					}
					else
					{
						_token = createOperatorToken(PerlTokenTypes.OPER_QMARK, "?");
					}
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mSUBST_OR_MATCH_OR_WORD(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = SUBST_OR_MATCH_OR_WORD;
		int _saveIndex;
		Token t1=null;
		Token n=null;
		Token t3=null;
		
		boolean synPredMatched1636 = false;
		if ((((_tokenSet_0.member(LA(1))) && (true) && (true) && (true))&&( !afterArrow ))) {
			int _m1636 = mark();
			synPredMatched1636 = true;
			inputState.guessing++;
			try {
				{
				{
				switch ( LA(1)) {
				case 'm':  case 'q':  case 's':  case 't':
				case 'y':
				{
					mSUBST_OR_MATCH_OPER(false);
					break;
				}
				case 'x':
				{
					match('x');
					break;
				}
				default:
				{
					throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
				}
				}
				}
				{
				switch ( LA(1)) {
				case '0':  case '1':  case '2':  case '3':
				case '4':  case '5':  case '6':  case '7':
				case '8':  case '9':  case 'A':  case 'B':
				case 'C':  case 'D':  case 'E':  case 'F':
				case 'G':  case 'H':  case 'I':  case 'J':
				case 'K':  case 'L':  case 'M':  case 'N':
				case 'O':  case 'P':  case 'Q':  case 'R':
				case 'S':  case 'T':  case 'U':  case 'V':
				case 'W':  case 'X':  case 'Y':  case 'Z':
				case 'a':  case 'b':  case 'c':  case 'd':
				case 'e':  case 'f':  case 'g':  case 'h':
				case 'i':  case 'j':  case 'k':  case 'l':
				case 'm':  case 'n':  case 'o':  case 'p':
				case 'q':  case 'r':  case 's':  case 't':
				case 'u':  case 'v':  case 'w':  case 'x':
				case 'y':  case 'z':
				{
					{
					switch ( LA(1)) {
					case 'A':  case 'B':  case 'C':  case 'D':
					case 'E':  case 'F':  case 'G':  case 'H':
					case 'I':  case 'J':  case 'K':  case 'L':
					case 'M':  case 'N':  case 'O':  case 'P':
					case 'Q':  case 'R':  case 'S':  case 'T':
					case 'U':  case 'V':  case 'W':  case 'X':
					case 'Y':  case 'Z':
					{
						matchRange('A','Z');
						break;
					}
					case 'a':  case 'b':  case 'c':  case 'd':
					case 'e':  case 'f':  case 'g':  case 'h':
					case 'i':  case 'j':  case 'k':  case 'l':
					case 'm':  case 'n':  case 'o':  case 'p':
					case 'q':  case 'r':  case 's':  case 't':
					case 'u':  case 'v':  case 'w':  case 'x':
					case 'y':  case 'z':
					{
						matchRange('a','z');
						break;
					}
					case '0':  case '1':  case '2':  case '3':
					case '4':  case '5':  case '6':  case '7':
					case '8':  case '9':
					{
						matchRange('0','9');
						break;
					}
					default:
					{
						throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
					}
					}
					}
					break;
				}
				case '\t':  case '\n':  case '\r':  case ' ':
				case '=':
				{
					{
					{
					_loop1635:
					do {
						if ((_tokenSet_2.member(LA(1)))) {
							mWS_CHAR(false);
						}
						else {
							break _loop1635;
						}
						
					} while (true);
					}
					match("=>");
					}
					break;
				}
				default:
				{
					throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
				}
				}
				}
				}
			}
			catch (RecognitionException pe) {
				synPredMatched1636 = false;
			}
			rewind(_m1636);
inputState.guessing--;
		}
		if ( synPredMatched1636 ) {
			if ( inputState.guessing==0 ) {
				notOper = true;
			}
			mWORD(true);
			t1=_returnToken;
			if ( inputState.guessing==0 ) {
				_token = t1;
			}
		}
		else {
			boolean synPredMatched1639 = false;
			if ((((LA(1)=='s'||LA(1)=='t'||LA(1)=='y') && (true) && (true) && (true))&&( !afterArrow && !afterSub ))) {
				int _m1639 = mark();
				synPredMatched1639 = true;
				inputState.guessing++;
				try {
					{
					{
					switch ( LA(1)) {
					case 't':
					{
						match("tr");
						break;
					}
					case 's':
					{
						match('s');
						break;
					}
					case 'y':
					{
						match('y');
						break;
					}
					default:
					{
						throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
					}
					}
					}
					matchNot('}');
					}
				}
				catch (RecognitionException pe) {
					synPredMatched1639 = false;
				}
				rewind(_m1639);
inputState.guessing--;
			}
			if ( synPredMatched1639 ) {
				mSUBST_EXPR(false);
				if ( inputState.guessing==0 ) {
					_ttype = PerlTokenTypes.SUBST_EXPR;
				}
			}
			else {
				boolean synPredMatched1643 = false;
				if ((((LA(1)=='m'||LA(1)=='q') && (true) && (true) && (true))&&( !afterArrow || afterDArrow ))) {
					int _m1643 = mark();
					synPredMatched1643 = true;
					inputState.guessing++;
					try {
						{
						{
						if ((LA(1)=='q') && (LA(2)=='q')) {
							match("qq");
						}
						else if ((LA(1)=='q') && (LA(2)=='x')) {
							match("qx");
						}
						else if ((LA(1)=='q') && (LA(2)=='w')) {
							match("qw");
						}
						else if ((LA(1)=='q') && (LA(2)=='r')) {
							match("qr");
						}
						else if ((LA(1)=='q') && (_tokenSet_9.member(LA(2)))) {
							match('q');
						}
						else if ((LA(1)=='m')) {
							match('m');
						}
						else {
							throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
						}
						
						}
						{
						match(_tokenSet_9);
						}
						}
					}
					catch (RecognitionException pe) {
						synPredMatched1643 = false;
					}
					rewind(_m1643);
inputState.guessing--;
				}
				if ( synPredMatched1643 ) {
					mMATCH_EXPR(false);
					if ( inputState.guessing==0 ) {
						_ttype = PerlTokenTypes.MATCH_EXPR;
					}
				}
				else {
					boolean synPredMatched1645 = false;
					if ((((LA(1) >= '0' && LA(1) <= '9')) && (true) && (true) && (true))) {
						int _m1645 = mark();
						synPredMatched1645 = true;
						inputState.guessing++;
						try {
							{
							mNUMBER(false);
							}
						}
						catch (RecognitionException pe) {
							synPredMatched1645 = false;
						}
						rewind(_m1645);
inputState.guessing--;
					}
					if ( synPredMatched1645 ) {
						mNUMBER(true);
						n=_returnToken;
						if ( inputState.guessing==0 ) {
							_token = n;
						}
					}
					else {
						boolean synPredMatched1648 = false;
						if (((LA(1)==':') && (true) && (true) && (true))) {
							int _m1648 = mark();
							synPredMatched1648 = true;
							inputState.guessing++;
							try {
								{
								match(':');
								{
								if ((LA(1)=='\uffff')) {
									_saveIndex=text.length();
									match('\uFFFF');
									text.setLength(_saveIndex);
								}
								else if ((_tokenSet_10.member(LA(1)))) {
									matchNot(':');
								}
								else {
									throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
								}
								
								}
								}
							}
							catch (RecognitionException pe) {
								synPredMatched1648 = false;
							}
							rewind(_m1648);
inputState.guessing--;
						}
						if ( synPredMatched1648 ) {
							match(':');
							if ( inputState.guessing==0 ) {
								
										glob = false;
										_token = createOperatorToken(PerlTokenTypes.OPER_COLON, ":");
									
							}
						}
						else if ((_tokenSet_0.member(LA(1))) && (true) && (true) && (true)) {
							mWORD(true);
							t3=_returnToken;
							if ( inputState.guessing==0 ) {
								_token = t3;
							}
						}
						else {
							throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
						}
						}}}}
						if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
							_token = makeToken(_ttype);
							_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
						}
						_returnToken = _token;
					}
					
	protected final void mSUBST_OR_MATCH_OPER(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = SUBST_OR_MATCH_OPER;
		int _saveIndex;
		
		{
		switch ( LA(1)) {
		case 't':
		{
			match("tr");
			break;
		}
		case 's':
		{
			match('s');
			break;
		}
		case 'y':
		{
			match('y');
			break;
		}
		case 'm':
		{
			match('m');
			break;
		}
		default:
			if ((LA(1)=='q') && (LA(2)=='q')) {
				match("qq");
			}
			else if ((LA(1)=='q') && (LA(2)=='x')) {
				match("qx");
			}
			else if ((LA(1)=='q') && (LA(2)=='w')) {
				match("qw");
			}
			else if ((LA(1)=='q') && (LA(2)=='r')) {
				match("qr");
			}
			else if ((LA(1)=='q') && (true)) {
				match('q');
			}
		else {
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		}
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mWS_CHAR(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = WS_CHAR;
		int _saveIndex;
		
		{
		switch ( LA(1)) {
		case ' ':
		{
			match(' ');
			break;
		}
		case '\t':
		{
			match('\t');
			break;
		}
		case '\n':
		{
			match('\n');
			break;
		}
		case '\r':
		{
			match('\r');
			break;
		}
		default:
		{
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		}
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mWORD(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = WORD;
		int _saveIndex;
		
		mID(false);
		if ( inputState.guessing==0 ) {
			
					String str = new String(text.getBuffer(),_begin,text.length()-_begin);
					
					if ("use".equals(str)) _ttype = PerlTokenTypes.KEYWORD_USE;
					else if ("sub".equals(str)) { afterSub = true; _ttype = PerlTokenTypes.KEYWORD_SUB; }
					else if ("package".equals(str)) { _ttype = PerlTokenTypes.KEYWORD_PACKAGE; }
					else if ("format".equals(str) && !afterSub) { format = true; _ttype = PerlTokenTypes.KEYWORD_FORMAT; }
					else if ("__END__".equals(str)) { _ttype = Token.EOF_TYPE; }
					else if ("__DATA__".equals(str)) { _ttype = Token.EOF_TYPE; }
					else if (!afterSub)
					{
						if (KEYWORDS1.contains(str))
					{
						if ("while".equals(str)) glob = true;
						_ttype = PerlTokenTypes.KEYWORD1;
					}
					else if (KEYWORDS2.contains(str))
					{
						glob = str.equals("unlink");
						_ttype = PerlTokenTypes.KEYWORD2;
					}
					else if (OPERATORS.contains(str) && !afterArrow && !notOper)
					{
						glob = false;
						_token = createOperatorToken(PerlTokenTypes.OPER_OTHER, str);
					}
					}
					else glob = false;
					
					slashRegexp = !(afterArrow || slashRegexp);
					qmarkRegexp = afterArrow = notOper = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mSUBST_EXPR(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = SUBST_EXPR;
		int _saveIndex;
		
		{
		switch ( LA(1)) {
		case 't':
		{
			match("tr");
			break;
		}
		case 's':
		{
			match('s');
			break;
		}
		case 'y':
		{
			match('y');
			break;
		}
		default:
		{
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		}
		}
		if ( inputState.guessing==0 ) {
			
					getParent().expectSubstExpr();
					slashRegexp = qmarkRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mMATCH_EXPR(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = MATCH_EXPR;
		int _saveIndex;
		
		{
		if ((LA(1)=='q') && (LA(2)=='q')) {
			match("qq");
		}
		else if ((LA(1)=='q') && (LA(2)=='x')) {
			match("qx");
		}
		else if ((LA(1)=='q') && (LA(2)=='w')) {
			match("qw");
		}
		else if ((LA(1)=='q') && (LA(2)=='r')) {
			match("qr");
		}
		else if ((LA(1)=='m')) {
			match('m');
		}
		else if ((LA(1)=='q') && (true)) {
			match('q');
		}
		else {
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		
		}
		if ( inputState.guessing==0 ) {
			
					getParent().expectStringSuffix(); // second
					getParent().expectString(); // first
					slashRegexp = qmarkRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mNUMBER(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = NUMBER;
		int _saveIndex;
		
		if ((LA(1)=='0') && (LA(2)=='x')) {
			{
			match("0x");
			{
			int _cnt1738=0;
			_loop1738:
			do {
				switch ( LA(1)) {
				case '0':  case '1':  case '2':  case '3':
				case '4':  case '5':  case '6':  case '7':
				case '8':  case '9':
				{
					matchRange('0','9');
					break;
				}
				case 'A':  case 'B':  case 'C':  case 'D':
				case 'E':  case 'F':
				{
					matchRange('A','F');
					break;
				}
				case 'a':  case 'b':  case 'c':  case 'd':
				case 'e':  case 'f':
				{
					matchRange('a','f');
					break;
				}
				case '_':
				{
					match('_');
					break;
				}
				default:
				{
					if ( _cnt1738>=1 ) { break _loop1738; } else {throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());}
				}
				}
				_cnt1738++;
			} while (true);
			}
			}
		}
		else if ((LA(1)=='0') && (LA(2)=='b')) {
			{
			match("0b");
			{
			int _cnt1741=0;
			_loop1741:
			do {
				switch ( LA(1)) {
				case '0':
				{
					match('0');
					break;
				}
				case '1':
				{
					match('1');
					break;
				}
				case '_':
				{
					match('_');
					break;
				}
				default:
				{
					if ( _cnt1741>=1 ) { break _loop1741; } else {throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());}
				}
				}
				_cnt1741++;
			} while (true);
			}
			}
		}
		else if (((LA(1) >= '0' && LA(1) <= '9')) && (true)) {
			{
			matchRange('0','9');
			}
			{
			_loop1744:
			do {
				switch ( LA(1)) {
				case '0':  case '1':  case '2':  case '3':
				case '4':  case '5':  case '6':  case '7':
				case '8':  case '9':
				{
					matchRange('0','9');
					break;
				}
				case '_':
				{
					match('_');
					break;
				}
				default:
				{
					break _loop1744;
				}
				}
			} while (true);
			}
			if ( inputState.guessing==0 ) {
				
						slashRegexp = qmarkRegexp = glob = afterArrow = afterDArrow = false;
						_ttype = PerlTokenTypes.NUMBER;
					
			}
		}
		else {
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_DARROW(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_DARROW;
		int _saveIndex;
		
		match("=>");
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_DARROW, "=>");
					afterArrow = afterDArrow = true;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_ARROW(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_ARROW;
		int _saveIndex;
		
		match("->");
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_ARROW, "->");
					qmarkRegexp = slashRegexp = false;
					afterArrow = true;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_DOUBLEEQ(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_DOUBLEEQ;
		int _saveIndex;
		
		match("==");
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_DOUBLEEQ, "==");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_NOTEQ(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_NOTEQ;
		int _saveIndex;
		
		match("!=");
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_NOTEQ, "!=");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_EQMATCH(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_EQMATCH;
		int _saveIndex;
		
		match("=~");
		if ( inputState.guessing==0 ) {
			afterArrow = afterDArrow = false; _token = createOperatorToken(PerlTokenTypes.OPER_EQMATCH, "=~");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_EQNOTMATCH(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_EQNOTMATCH;
		int _saveIndex;
		
		match("!~");
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_EQNOTMATCH, "!~");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_MINUSMINUS(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_MINUSMINUS;
		int _saveIndex;
		
		match("--");
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_MINUSMINUS, "--");
					qmarkRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_MINUSEQ(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_MINUSEQ;
		int _saveIndex;
		
		match("-=");
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_PLUSPLUS, "-=");
					qmarkRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_PLUSPLUS(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_PLUSPLUS;
		int _saveIndex;
		
		match("++");
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_PLUSPLUS, "++");
					qmarkRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_PLUSEQ(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_PLUSEQ;
		int _saveIndex;
		
		match("+=");
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_PLUSPLUS, "+=");
					qmarkRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_COMMA(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_COMMA;
		int _saveIndex;
		
		match(',');
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_COMMA, ",");
					afterArrow = afterDArrow = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_EQ(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_EQ;
		int _saveIndex;
		
		if (!( !format ))
		  throw new SemanticException(" !format ");
		match('=');
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_EQ, "=");
					glob = true;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_DIV(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_DIV;
		int _saveIndex;
		
		match('/');
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_DIV, "/");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_PLUS(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_PLUS;
		int _saveIndex;
		
		match('+');
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_PLUS, "+");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_MINUS(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_MINUS;
		int _saveIndex;
		
		match('-');
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_MINUS, "-");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_DOTDOT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_DOTDOT;
		int _saveIndex;
		
		match("..");
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_DOTDOT, "..");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_DOT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_DOT;
		int _saveIndex;
		
		match('.');
		if ( inputState.guessing==0 ) {
			afterArrow = afterDArrow = false; _token = createOperatorToken(PerlTokenTypes.OPER_DOT, ".");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_BSLASH(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_BSLASH;
		int _saveIndex;
		
		match('\\');
		if ( inputState.guessing==0 ) {
			_token = createOperatorToken(PerlTokenTypes.OPER_BSLASH, "\\");
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPEN_PAREN(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_PAREN;
		int _saveIndex;
		
		match('(');
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPEN_PAREN, "(");
					if (afterSub) { afterSub = false; proto = true; }
					format = false;
					glob = qmarkRegexp = slashRegexp = true;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mCLOSE_PAREN(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = CLOSE_PAREN;
		int _saveIndex;
		
		match(')');
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.CLOSE_PAREN, ")");
					glob = qmarkRegexp = slashRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPEN_BRACKET(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_BRACKET;
		int _saveIndex;
		
		match('[');
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPEN_BRACKET, "[");
					format = false;
					glob = qmarkRegexp = slashRegexp = true;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mCLOSE_BRACKET(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = CLOSE_BRACKET;
		int _saveIndex;
		
		match(']');
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.CLOSE_BRACKET, "]");
					glob = qmarkRegexp = slashRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mFORMAT_STMT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = FORMAT_STMT;
		int _saveIndex;
		
		if (!( format ))
		  throw new SemanticException(" format ");
		match("=");
		if ( inputState.guessing==0 ) {
			
					format = false;
					getParent().expectFormatEnd();
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mVAR_WITH_CURLY(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = VAR_WITH_CURLY;
		int _saveIndex;
		
		boolean synPredMatched1679 = false;
		if (((LA(1)=='$'||LA(1)=='%'||LA(1)=='@') && (_tokenSet_6.member(LA(2))) && (true) && (true))) {
			int _m1679 = mark();
			synPredMatched1679 = true;
			inputState.guessing++;
			try {
				{
				mVAR(false);
				{
				switch ( LA(1)) {
				case '\t':  case '\n':  case '\r':  case ' ':
				{
					mWS(false);
					break;
				}
				case '{':
				{
					break;
				}
				default:
				{
					throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
				}
				}
				}
				match('{');
				}
			}
			catch (RecognitionException pe) {
				synPredMatched1679 = false;
			}
			rewind(_m1679);
inputState.guessing--;
		}
		if ( synPredMatched1679 ) {
			mVAR(false);
			{
			if ((_tokenSet_2.member(LA(1)))) {
				mWS(false);
			}
			else {
			}
			
			}
			if ( inputState.guessing==0 ) {
				getParent().expectString();
			}
		}
		else {
			boolean synPredMatched1682 = false;
			if (((LA(1)=='$'||LA(1)=='%'||LA(1)=='@') && (_tokenSet_6.member(LA(2))) && (true) && (true))) {
				int _m1682 = mark();
				synPredMatched1682 = true;
				inputState.guessing++;
				try {
					{
					mVAR(false);
					}
				}
				catch (RecognitionException pe) {
					synPredMatched1682 = false;
				}
				rewind(_m1682);
inputState.guessing--;
			}
			if ( synPredMatched1682 ) {
				mVAR(false);
			}
			else {
				throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
			}
			}
			if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
				_token = makeToken(_ttype);
				_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
			}
			_returnToken = _token;
		}
		
	public final void mPROC_REF(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = PROC_REF;
		int _saveIndex;
		
		match('&');
		mID(false);
		if ( inputState.guessing==0 ) {
			qmarkRegexp = slashRegexp = false;
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_LSHIFT_OR_HEREDOC(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_LSHIFT_OR_HEREDOC;
		int _saveIndex;
		
		boolean synPredMatched1686 = false;
		if (((LA(1)=='<') && (LA(2)=='<') && (_tokenSet_11.member(LA(3))))) {
			int _m1686 = mark();
			synPredMatched1686 = true;
			inputState.guessing++;
			try {
				{
				mOPEN_HEREDOC(false);
				}
			}
			catch (RecognitionException pe) {
				synPredMatched1686 = false;
			}
			rewind(_m1686);
inputState.guessing--;
		}
		if ( synPredMatched1686 ) {
			mOPEN_HEREDOC(false);
			if ( inputState.guessing==0 ) {
				_ttype = PerlTokenTypes.OPEN_HEREDOC;
			}
		}
		else {
			boolean synPredMatched1690 = false;
			if (((LA(1)=='<') && (LA(2)=='<') && (true))) {
				int _m1690 = mark();
				synPredMatched1690 = true;
				inputState.guessing++;
				try {
					{
					match("<<");
					{
					if ((_tokenSet_2.member(LA(1))) && (_tokenSet_12.member(LA(2)))) {
						mWS(false);
					}
					else if ((_tokenSet_12.member(LA(1))) && (true)) {
					}
					else {
						throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
					}
					
					}
					{
					match(_tokenSet_12);
					}
					}
				}
				catch (RecognitionException pe) {
					synPredMatched1690 = false;
				}
				rewind(_m1690);
inputState.guessing--;
			}
			if ( synPredMatched1690 ) {
				mOPER_LSHIFT(false);
				if ( inputState.guessing==0 ) {
					_token = createOperatorToken(PerlTokenTypes.OPER_LSHIFT, "<<");
				}
			}
			else {
				throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
			}
			}
			if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
				_token = makeToken(_ttype);
				_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
			}
			_returnToken = _token;
		}
		
	protected final void mOPEN_HEREDOC(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_HEREDOC;
		int _saveIndex;
		
		{
		boolean synPredMatched1696 = false;
		if (((LA(1)=='<') && (LA(2)=='<') && (_tokenSet_13.member(LA(3))) && ((LA(4) >= '\u0000' && LA(4) <= '\uffff')))) {
			int _m1696 = mark();
			synPredMatched1696 = true;
			inputState.guessing++;
			try {
				{
				match("<<");
				{
				switch ( LA(1)) {
				case '\t':  case '\n':  case '\r':  case ' ':
				{
					mWS(false);
					break;
				}
				case '"':
				{
					break;
				}
				default:
				{
					throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
				}
				}
				}
				match('"');
				}
			}
			catch (RecognitionException pe) {
				synPredMatched1696 = false;
			}
			rewind(_m1696);
inputState.guessing--;
		}
		if ( synPredMatched1696 ) {
			match("<<");
			{
			switch ( LA(1)) {
			case '\t':  case '\n':  case '\r':  case ' ':
			{
				_saveIndex=text.length();
				mWS(false);
				text.setLength(_saveIndex);
				break;
			}
			case '"':
			{
				break;
			}
			default:
			{
				throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
			}
			}
			}
			_saveIndex=text.length();
			match('"');
			text.setLength(_saveIndex);
			{
			_loop1700:
			do {
				if ((LA(1)=='\\') && (LA(2)=='"') && ((LA(3) >= '\u0000' && LA(3) <= '\uffff')) && (true)) {
					match("\\\"");
				}
				else if ((_tokenSet_14.member(LA(1))) && ((LA(2) >= '\u0000' && LA(2) <= '\uffff')) && (true) && (true)) {
					{
					match(_tokenSet_14);
					}
				}
				else {
					break _loop1700;
				}
				
			} while (true);
			}
		}
		else {
			boolean synPredMatched1703 = false;
			if (((LA(1)=='<') && (LA(2)=='<') && (_tokenSet_15.member(LA(3))) && ((LA(4) >= '\u0000' && LA(4) <= '\uffff')))) {
				int _m1703 = mark();
				synPredMatched1703 = true;
				inputState.guessing++;
				try {
					{
					match("<<");
					{
					switch ( LA(1)) {
					case '\t':  case '\n':  case '\r':  case ' ':
					{
						mWS(false);
						break;
					}
					case '\'':
					{
						break;
					}
					default:
					{
						throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
					}
					}
					}
					match("'");
					}
				}
				catch (RecognitionException pe) {
					synPredMatched1703 = false;
				}
				rewind(_m1703);
inputState.guessing--;
			}
			if ( synPredMatched1703 ) {
				match("<<");
				{
				switch ( LA(1)) {
				case '\t':  case '\n':  case '\r':  case ' ':
				{
					_saveIndex=text.length();
					mWS(false);
					text.setLength(_saveIndex);
					break;
				}
				case '\'':
				{
					break;
				}
				default:
				{
					throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
				}
				}
				}
				_saveIndex=text.length();
				match("'");
				text.setLength(_saveIndex);
				{
				_loop1707:
				do {
					if ((LA(1)=='\\') && (LA(2)=='\'') && ((LA(3) >= '\u0000' && LA(3) <= '\uffff')) && (true)) {
						match("\\'");
					}
					else if ((_tokenSet_16.member(LA(1))) && ((LA(2) >= '\u0000' && LA(2) <= '\uffff')) && (true) && (true)) {
						{
						match(_tokenSet_16);
						}
					}
					else {
						break _loop1707;
					}
					
				} while (true);
				}
			}
			else {
				boolean synPredMatched1710 = false;
				if (((LA(1)=='<') && (LA(2)=='<') && (_tokenSet_17.member(LA(3))) && ((LA(4) >= '\u0000' && LA(4) <= '\uffff')))) {
					int _m1710 = mark();
					synPredMatched1710 = true;
					inputState.guessing++;
					try {
						{
						match("<<");
						{
						switch ( LA(1)) {
						case '\t':  case '\n':  case '\r':  case ' ':
						{
							mWS(false);
							break;
						}
						case '`':
						{
							break;
						}
						default:
						{
							throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
						}
						}
						}
						match('`');
						}
					}
					catch (RecognitionException pe) {
						synPredMatched1710 = false;
					}
					rewind(_m1710);
inputState.guessing--;
				}
				if ( synPredMatched1710 ) {
					match("<<");
					{
					switch ( LA(1)) {
					case '\t':  case '\n':  case '\r':  case ' ':
					{
						_saveIndex=text.length();
						mWS(false);
						text.setLength(_saveIndex);
						break;
					}
					case '`':
					{
						break;
					}
					default:
					{
						throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
					}
					}
					}
					_saveIndex=text.length();
					match('`');
					text.setLength(_saveIndex);
					{
					_loop1714:
					do {
						if ((LA(1)=='\\') && (LA(2)=='`') && ((LA(3) >= '\u0000' && LA(3) <= '\uffff')) && (true)) {
							match("\\`");
						}
						else if ((_tokenSet_18.member(LA(1))) && ((LA(2) >= '\u0000' && LA(2) <= '\uffff')) && (true) && (true)) {
							{
							match(_tokenSet_18);
							}
						}
						else {
							break _loop1714;
						}
						
					} while (true);
					}
				}
				else {
					boolean synPredMatched1717 = false;
					if (((LA(1)=='<') && (LA(2)=='<') && (_tokenSet_0.member(LA(3))))) {
						int _m1717 = mark();
						synPredMatched1717 = true;
						inputState.guessing++;
						try {
							{
							match("<<");
							{
							switch ( LA(1)) {
							case '\t':  case '\n':  case '\r':  case ' ':
							{
								mWS(false);
								break;
							}
							case '0':  case '1':  case '2':  case '3':
							case '4':  case '5':  case '6':  case '7':
							case '8':  case '9':  case ':':  case 'A':
							case 'B':  case 'C':  case 'D':  case 'E':
							case 'F':  case 'G':  case 'H':  case 'I':
							case 'J':  case 'K':  case 'L':  case 'M':
							case 'N':  case 'O':  case 'P':  case 'Q':
							case 'R':  case 'S':  case 'T':  case 'U':
							case 'V':  case 'W':  case 'X':  case 'Y':
							case 'Z':  case '_':  case 'a':  case 'b':
							case 'c':  case 'd':  case 'e':  case 'f':
							case 'g':  case 'h':  case 'i':  case 'j':
							case 'k':  case 'l':  case 'm':  case 'n':
							case 'o':  case 'p':  case 'q':  case 'r':
							case 's':  case 't':  case 'u':  case 'v':
							case 'w':  case 'x':  case 'y':  case 'z':
							{
								break;
							}
							default:
							{
								throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
							}
							}
							}
							mWORD_CHAR(false);
							}
						}
						catch (RecognitionException pe) {
							synPredMatched1717 = false;
						}
						rewind(_m1717);
inputState.guessing--;
					}
					if ( synPredMatched1717 ) {
						match("<<");
						{
						int _cnt1719=0;
						_loop1719:
						do {
							if ((_tokenSet_0.member(LA(1))) && ((LA(2) >= '\u0000' && LA(2) <= '\uffff')) && (true) && (true)) {
								mWORD_CHAR(false);
							}
							else {
								if ( _cnt1719>=1 ) { break _loop1719; } else {throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());}
							}
							
							_cnt1719++;
						} while (true);
						}
					}
					else {
						throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
					}
					}}}
					}
					{
					_loop1721:
					do {
						if ((_tokenSet_5.member(LA(1)))) {
							_saveIndex=text.length();
							mNOT_NEWLINE(false);
							text.setLength(_saveIndex);
						}
						else {
							break _loop1721;
						}
						
					} while (true);
					}
					if ( inputState.guessing==0 ) {
						if (LA(1) != EOF_CHAR) getParent().expectHereDocEnd(new String(text.getBuffer(),_begin,text.length()-_begin));
					}
					{
					switch ( LA(1)) {
					case '\n':  case '\r':
					{
						mNEWLINE(false);
						break;
					}
					case '\uffff':
					{
						_saveIndex=text.length();
						match('\uFFFF');
						text.setLength(_saveIndex);
						break;
					}
					default:
					{
						throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
					}
					}
					}
					if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
						_token = makeToken(_ttype);
						_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
					}
					_returnToken = _token;
				}
				
	protected final void mOPER_LSHIFT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_LSHIFT;
		int _saveIndex;
		
		match("<<");
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mWORD_CHAR(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = WORD_CHAR;
		int _saveIndex;
		
		{
		switch ( LA(1)) {
		case 'A':  case 'B':  case 'C':  case 'D':
		case 'E':  case 'F':  case 'G':  case 'H':
		case 'I':  case 'J':  case 'K':  case 'L':
		case 'M':  case 'N':  case 'O':  case 'P':
		case 'Q':  case 'R':  case 'S':  case 'T':
		case 'U':  case 'V':  case 'W':  case 'X':
		case 'Y':  case 'Z':
		{
			matchRange('A','Z');
			break;
		}
		case 'a':  case 'b':  case 'c':  case 'd':
		case 'e':  case 'f':  case 'g':  case 'h':
		case 'i':  case 'j':  case 'k':  case 'l':
		case 'm':  case 'n':  case 'o':  case 'p':
		case 'q':  case 'r':  case 's':  case 't':
		case 'u':  case 'v':  case 'w':  case 'x':
		case 'y':  case 'z':
		{
			matchRange('a','z');
			break;
		}
		case '0':  case '1':  case '2':  case '3':
		case '4':  case '5':  case '6':  case '7':
		case '8':  case '9':
		{
			matchRange('0','9');
			break;
		}
		case '_':
		{
			match('_');
			break;
		}
		case ':':
		{
			match(':');
			break;
		}
		default:
		{
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		}
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mGLOB(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = GLOB;
		int _saveIndex;
		
		if (!( glob ))
		  throw new SemanticException(" glob ");
		match('<');
		{
		_loop1726:
		do {
			if ((_tokenSet_19.member(LA(1)))) {
				{
				match(_tokenSet_19);
				}
			}
			else {
				break _loop1726;
			}
			
		} while (true);
		}
		{
		switch ( LA(1)) {
		case '>':
		{
			match('>');
			break;
		}
		case '\uffff':
		{
			_saveIndex=text.length();
			match('\uFFFF');
			text.setLength(_saveIndex);
			break;
		}
		default:
		{
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		}
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_RSHIFT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_RSHIFT;
		int _saveIndex;
		
		match(">>");
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_RSHIFT, ">>");
					qmarkRegexp = slashRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_GT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_GT;
		int _saveIndex;
		
		match('>');
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_GT, ">");
					qmarkRegexp = slashRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPER_LT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPER_LT;
		int _saveIndex;
		
		if (!( !glob ))
		  throw new SemanticException(" !glob ");
		match('<');
		if ( inputState.guessing==0 ) {
			
					_token = createOperatorToken(PerlTokenTypes.OPER_LT, "<");
					qmarkRegexp = slashRegexp = false;
				
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOPEN_POD(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_POD;
		int _saveIndex;
		
		if (!( getColumn() == 1 ))
		  throw new SemanticException(" getColumn() == 1 ");
		match('=');
		mID(false);
		{
		_loop1733:
		do {
			if ((_tokenSet_5.member(LA(1)))) {
				mNOT_NEWLINE(false);
			}
			else {
				break _loop1733;
			}
			
		} while (true);
		}
		{
		switch ( LA(1)) {
		case '\n':  case '\r':
		{
			_saveIndex=text.length();
			mNEWLINE(false);
			text.setLength(_saveIndex);
			break;
		}
		case '\uffff':
		{
			_saveIndex=text.length();
			match('\uFFFF');
			text.setLength(_saveIndex);
			break;
		}
		default:
		{
			throw new NoViableAltForCharException((char)LA(1), getFilename(), getLine(), getColumn());
		}
		}
		}
		if ( inputState.guessing==0 ) {
			getParent().expectPODEnd();
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	public final void mOTHER(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OTHER;
		int _saveIndex;
		
		{
		match(_tokenSet_20);
		}
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mKEYWORD1(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = KEYWORD1;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mKEYWORD2(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = KEYWORD2;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mKEYWORD_USE(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = KEYWORD_USE;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mKEYWORD_SUB(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = KEYWORD_SUB;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mKEYWORD_FORMAT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = KEYWORD_FORMAT;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	protected final void mOPEN_QUOTE(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
		int _ttype; Token _token=null; int _begin=text.length();
		_ttype = OPEN_QUOTE;
		int _saveIndex;
		
		if ( _createToken && _token==null && _ttype!=Token.SKIP ) {
			_token = makeToken(_ttype);
			_token.setText(new String(text.getBuffer(), _begin, text.length()-_begin));
		}
		_returnToken = _token;
	}
	
	
	private static final long[] mk_tokenSet_0() {
		long[] data = new long[1025];
		data[0]=576179277326712832L;
		data[1]=576460745995190270L;
		return data;
	}
	public static final BitSet _tokenSet_0 = new BitSet(mk_tokenSet_0());
	private static final long[] mk_tokenSet_1() {
		long[] data = new long[2048];
		data[0]=-1152921504606856193L;
		for (int i = 1; i<=1023; i++) { data[i]=-1L; }
		return data;
	}
	public static final BitSet _tokenSet_1 = new BitSet(mk_tokenSet_1());
	private static final long[] mk_tokenSet_2() {
		long[] data = new long[1025];
		data[0]=4294977024L;
		return data;
	}
	public static final BitSet _tokenSet_2 = new BitSet(mk_tokenSet_2());
	private static final long[] mk_tokenSet_3() {
		long[] data = new long[1025];
		data[0]=4604204941312L;
		data[1]=1L;
		return data;
	}
	public static final BitSet _tokenSet_3 = new BitSet(mk_tokenSet_3());
	private static final long[] mk_tokenSet_4() {
		long[] data = new long[1025];
		data[0]=576465635681248768L;
		data[1]=2415919105L;
		return data;
	}
	public static final BitSet _tokenSet_4 = new BitSet(mk_tokenSet_4());
	private static final long[] mk_tokenSet_5() {
		long[] data = new long[2048];
		data[0]=-9217L;
		for (int i = 1; i<=1022; i++) { data[i]=-1L; }
		data[1023]=9223372036854775807L;
		return data;
	}
	public static final BitSet _tokenSet_5 = new BitSet(mk_tokenSet_5());
	private static final long[] mk_tokenSet_6() {
		long[] data = new long[2048];
		data[0]=576183915891392512L;
		data[1]=1152921498298613759L;
		data[1023]=-9223372036854775808L;
		return data;
	}
	public static final BitSet _tokenSet_6 = new BitSet(mk_tokenSet_6());
	private static final long[] mk_tokenSet_7() {
		long[] data = new long[1025];
		data[0]=-287948909764935680L;
		data[1]=5764607531489951745L;
		return data;
	}
	public static final BitSet _tokenSet_7 = new BitSet(mk_tokenSet_7());
	private static final long[] mk_tokenSet_8() {
		long[] data = new long[2048];
		data[0]=-1L;
		data[1]=-2305843009213693953L;
		for (int i = 2; i<=1022; i++) { data[i]=-1L; }
		data[1023]=9223372036854775807L;
		return data;
	}
	public static final BitSet _tokenSet_8 = new BitSet(mk_tokenSet_8());
	private static final long[] mk_tokenSet_9() {
		long[] data = new long[2048];
		data[0]=-287948905469977601L;
		data[1]=-2882303755074666497L;
		for (int i = 2; i<=1023; i++) { data[i]=-1L; }
		return data;
	}
	public static final BitSet _tokenSet_9 = new BitSet(mk_tokenSet_9());
	private static final long[] mk_tokenSet_10() {
		long[] data = new long[2048];
		data[0]=-288230376151711745L;
		for (int i = 1; i<=1022; i++) { data[i]=-1L; }
		data[1023]=9223372036854775807L;
		return data;
	}
	public static final BitSet _tokenSet_10 = new BitSet(mk_tokenSet_10());
	private static final long[] mk_tokenSet_11() {
		long[] data = new long[1025];
		data[0]=576179848557372928L;
		data[1]=576460750290157566L;
		return data;
	}
	public static final BitSet _tokenSet_11 = new BitSet(mk_tokenSet_11());
	private static final long[] mk_tokenSet_12() {
		long[] data = new long[2048];
		data[0]=-566935683073L;
		data[1]=-4429185023L;
		for (int i = 2; i<=1023; i++) { data[i]=-1L; }
		return data;
	}
	public static final BitSet _tokenSet_12 = new BitSet(mk_tokenSet_12());
	private static final long[] mk_tokenSet_13() {
		long[] data = new long[1025];
		data[0]=21474846208L;
		return data;
	}
	public static final BitSet _tokenSet_13 = new BitSet(mk_tokenSet_13());
	private static final long[] mk_tokenSet_14() {
		long[] data = new long[2048];
		data[0]=-17179878401L;
		for (int i = 1; i<=1022; i++) { data[i]=-1L; }
		data[1023]=9223372036854775807L;
		return data;
	}
	public static final BitSet _tokenSet_14 = new BitSet(mk_tokenSet_14());
	private static final long[] mk_tokenSet_15() {
		long[] data = new long[1025];
		data[0]=554050790912L;
		return data;
	}
	public static final BitSet _tokenSet_15 = new BitSet(mk_tokenSet_15());
	private static final long[] mk_tokenSet_16() {
		long[] data = new long[2048];
		data[0]=-549755823105L;
		for (int i = 1; i<=1022; i++) { data[i]=-1L; }
		data[1023]=9223372036854775807L;
		return data;
	}
	public static final BitSet _tokenSet_16 = new BitSet(mk_tokenSet_16());
	private static final long[] mk_tokenSet_17() {
		long[] data = new long[1025];
		data[0]=4294977024L;
		data[1]=4294967296L;
		return data;
	}
	public static final BitSet _tokenSet_17 = new BitSet(mk_tokenSet_17());
	private static final long[] mk_tokenSet_18() {
		long[] data = new long[2048];
		data[0]=-9217L;
		data[1]=-4294967297L;
		for (int i = 2; i<=1022; i++) { data[i]=-1L; }
		data[1023]=9223372036854775807L;
		return data;
	}
	public static final BitSet _tokenSet_18 = new BitSet(mk_tokenSet_18());
	private static final long[] mk_tokenSet_19() {
		long[] data = new long[2048];
		data[0]=-5764607523034244097L;
		for (int i = 1; i<=1022; i++) { data[i]=-1L; }
		data[1023]=9223372036854775807L;
		return data;
	}
	public static final BitSet _tokenSet_19 = new BitSet(mk_tokenSet_19());
	private static final long[] mk_tokenSet_20() {
		long[] data = new long[2048];
		for (int i = 0; i<=1022; i++) { data[i]=-1L; }
		data[1023]=9223372036854775807L;
		return data;
	}
	public static final BitSet _tokenSet_20 = new BitSet(mk_tokenSet_20());
	
	}
